export const APPLY_STORED_STATE = 'APPLY_STORED_STATE';
export const DESERIALIZE = 'DESERIALIZE';
export const DOCUMENT_HEAD_LINK_SET = 'DOCUMENT_HEAD_LINK_SET';
export const DOCUMENT_HEAD_META_SET = 'DOCUMENT_HEAD_META_SET';
export const DOCUMENT_HEAD_TITLE_SET = 'DOCUMENT_HEAD_TITLE_SET';
export const DOCUMENT_HEAD_UNREAD_COUNT_SET = 'DOCUMENT_HEAD_UNREAD_COUNT_SET';
export const LOCALE_SET = 'LOCALE_SET';
export const ROUTE_SET = 'ROUTE_SET';
export const SECTION_SET = 'SECTION_SET';
export const SERIALIZE = 'SERIALIZE';

export const RECEIVED_TRANSLATIONS = 'RECEIVED_TRANSLATIONS';
